import Head from 'next/head'
import ModalAdd from './modalAdd'
import {useState}  from 'react'

export default function Home() {
  const [displayGo, setDisplayGo] = useState('none')
  const [heightGo, setHeigthGo] = useState('0px')
  
  return (
    <div>
      <Head>
        <title>GoPlant</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
  
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"/>
      
        <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </Head>

      <div id="blackWindow" style={{display: displayGo}} onClick={()=>{
        if(displayGo === 'none'){
          setDisplayGo('flex')
        }else{
          setDisplayGo('none')
          setHeigthGo('0px')
        }
      }}></div>
      <div id="blackWindowHome">
      <div class="container-fluid">  
          <h1 class="mt-5 mb-3" style={{color: '#FFF'}}>Sua Plantação</h1>
          <div class="row gap-4">
            <div class="col">
                <div class="left-col">
                  <h4>Tomate</h4>
                  <h4>Fase</h4>
                </div>
                <div class="right-col"><div className="img-right-col"></div></div>
            </div>
            <div class="col">
              <div class="left-col">
                  <h4>Tomate</h4>
                  <h4>Fase</h4>
              </div>
              <div class="right-col"><div className="img-right-col"></div></div>
            </div>
            <div class="col">
              <div class="left-col">
                  <h4>Tomate</h4>
                  <h4>Fase</h4>
              </div>
                  <div class="right-col"><div className="img-right-col"></div></div>  
            </div>
            <div class="col">
              <div class="left-col">
                  <h4>Tomate</h4>
                  <h4>Fase</h4>
              </div>
                  <div class="right-col"><div className="img-right-col"></div></div>  
            </div>
          </div>
          <div class="buttonAdd mt-5">
              <button id="buttonAdd" onClick={()=>{
                if(displayGo === 'none'){
                  setDisplayGo('flex')
                  setHeigthGo('calc(100vh - 120px)')
                }else{
                  setDisplayGo('none')
                }
              }}>+</button>
          </div>
          <ModalAdd display={displayGo} height ={heightGo}/>
        </div>
      </div>
    </div>
  )
}
